__author__ = 'pfftman'

aliases = {"lvoa": "Lvoa-C", "lwm4": "Lightweight M4",
           "fm": "Final Measure", "ls": "Lone Star",
           "mdr": "MDR Battle Rifle", "urban mdr": "MDR Battle Rifle",
           "ab": "Alpha Bridge", "alphabridge": "Alpha Bridge",
           "g36": "G36 C", "sasg": "sasg-12",
           "aug": "Tactical AUG A3P", "vector": "Vector 45 ACP",
           "magnum": "586 Magnum", "bm ak": "Black Market AK-74",
           "bm rpk": "Black Market RPK-74 E", "d3": "D3-Fnc",
           "sb": "Striker", "sc": "Sentry",
           "tac": "Tactician", "rec": "Reclaimer",
           "famas": "Bullfrog", "ninjabike": "Ninjabike Messenger Bag",
           "ninja": "Ninjabike Messenger Bag", "ferro's": "Ferro'S Oxygen Mask",
           "ferro's mask": "Ferro'S Oxygen Mask",
           "skull gloves": "Skulls Mc Gloves", "skulls": "Skulls Mc Gloves",
           "barret's vest": "Barrett's Bulletproof", "barret's": "Barrett's Bulletproof",
           "barret's chest piece": "Barrett's Bulletproof", "barret's chest": "Barrett's Bulletproof",
           "shortbows": "Shortbow Championship Pads", "shortbow": "Shortbow Championship Pads",
           "bliss holster": "Colonel Bliss's Holster", "scar-h": "Military SCAR-H", "svd": "Surplus SVD",
           "srs": "Covert SRS", "m44": "Custom m44", "classic m44": "Classic m44 carbine",
           "ak-47": "Classic AK-47", "ak": "Classic AK-47", "military ak-47": "Military AK-47M",
           "military ak": "military AK-47", "black market ak": "Black Market AK-74",
           "pred": "Predators mark", "pred mark": "Predators Mark",
           "sh": "Skill Haste", "dte": "Damage vs Elites", "ead": "Enemy Armor Damage",
           "damage to elites": "Damage vs Elites", "chd": "crit damage", "chc": "crit chance",
           "critical hit damage": "crit damage", "critical hit chance": "crit chance",
           "self-preserved": "selfpreserved"}


vendor_aliases = {
    "chd": "critical hit damage", "chc": "critical hit chance", "vest": "chest",
    "pred": "Predator's mark", "sp": "Skill Power", "ar damage": "Assault Rifle Damage",
    "dte": "damage to elites", "sh": "Skill haste",
    "lvoa": "Lvoa-C", "lwm4": "Lightweight M4",
    "rpk": "rpk-74",
    "fm": "Final Measure", "ls": "Lone Star",
        "urban mdr": "MDR Battle Rifle",
    "ab": "Alpha Bridge", "alphabridge": "Alpha Bridge",
    "sasg": "sasg-12",
    "magnum": "586 Magnum", "bm ak": "Black Market AK-74",
    "bm rpk": "Black Market RPK-74 E", "d3": "D3-Fnc",
    "sb": "Striker", "sc": "Sentry",
    "tac": "Tactician", "rec": "Reclaimer",
    "famas": "Bullfrog", "ninjabike": "Ninjabike Messenger Bag",
    "ninja": "Ninjabike Messenger Bag", "ferro's": "Ferro'S Oxygen Mask",
    "ferro's mask": "Ferro'S Oxygen Mask",
    "skull gloves": "Skulls Mc Gloves", "skulls": "Skulls Mc Gloves",
    "barret's vest": "Barrett's Bulletproof", "barret's": "Barrett's Bulletproof",
    "barret's chest piece": "Barrett's Bulletproof", "barret's chest": "Barrett's Bulletproof",
    "shortbows": "Shortbow Championship Pads", "shortbow": "Shortbow Championship Pads",
    "bliss holster": "Colonel Bliss's Holster", "classic m44": "Classic m44 carbine",
    "ak": "AK-47", "military ak-47": "Military AK-47M",
    "military ak": "military AK-47", "black market ak": "Black Market AK-74",
    "pred mark": "Predator's Mark",
    "sh": "Skill Haste", "ead": "Enemy Armor Damage",
    "extended mag": "extended magazine"
}