__author__ = 'pfftman'

aliases = {"lvoa": "Lvoa-C", "lwm4": "Lightweight M4",
           "fm": "Final Measure", "ls": "Lone Star",
           "mdr": "MDR Battle Rifle", "urban mdr": "MDR Battle Rifle",
           "ab": "Alpha Bridge", "alphabridge": "Alpha Bridge",
           "g36": "G36 C", "sasg": "sasg-12",
           "aug": "Tactical AUG A3P", "vector": "Vector 45 ACP",
           "magnum": "586 Magnum", "bm ak": "Black Market AK-74",
           "bm rpk": "Black Market RPK-74 E", "d3": "D3-Fnc",
           "sb": "Striker", "sc": "Sentry",
           "tac": "Tactician", "rec": "Reclaimer",
           "famas": "Bullfrog", "ninjabike": "Ninjabike Messenger Bag",
           "ninja": "Ninjabike Messenger Bag", "ferro's": "Ferro'S Oxygen Mask",
           "ferro's mask": "Ferro'S Oxygen Mask",
           "skull gloves": "Skulls Mc Gloves", "skulls": "Skulls Mc Gloves",
           "barret's vest": "Barrett's Bulletproof", "barret's": "Barrett's Bulletproof",
           "barret's chest piece": "Barrett's Bulletproof", "barret's chest": "Barrett's Bulletproof",
           "shortbows": "Shortbow Championship Pads", "shortbow": "Shortbow Championship Pads",
           "bliss holster": "Colonel Bliss's Holster", "scar-h": "Military SCAR-H", "svd": "Surplus SVD",
           "srs": "Covert SRS", "m44": "Custom m44", "classic m44": "Classic m44 carbine",
           "AK-47": "Classic AK-47", "AK": "Classic AK-47", "Military AK-47": "Military AK-47M",
           "Military AK": "Military AK-47", "Black Market AK": "Black Market AK-74"}